/* ============================================================
   48x48 像素精灵系统 - 4角色 x 5动画状态
   ============================================================ */

// 辅助: 将紧凑模板居中展开为48x48数组
function _expand(tpl, w, h) {
  const r = [], tp = (48 - h) >> 1, bp = 48 - tp - h;
  for (let i = 0; i < tp; i++) r.push(".".repeat(48));
  for (const row of tpl) {
    const lp = (48 - w) >> 1, rp = 48 - lp - row.length;
    r.push(".".repeat(lp) + row + ".".repeat(rp));
  }
  for (let i = 0; i < bp; i++) r.push(".".repeat(48));
  return r;
}

// 解析函数: 将字符串数组转为整数数组
function parseSprite(strArr, palMap) {
  return strArr.map(row => {
    const arr = new Array(48);
    for (let i = 0; i < 48; i++) arr[i] = palMap[row[i]] !== undefined ? palMap[row[i]] : 0;
    return arr;
  });
}

// ============================================================
// 1. KNIGHT (骑士) - 银灰板甲+深蓝披风+剑盾, 二头身Q版, 方正厚重
// ============================================================
const KNIGHT_PAL = { '.':0, 'k':1, 'B':2, 'b':3, 'S':4, 's':5, 'R':6, 'W':7, 'L':8 };

const _KW = 28, _KH = 35;

const K_IDLE = _expand([
  "............kkkk........",
  "...........kRRRRk.......",
  "..........kRRRRRRk......",
  "..........kSSSSSSk......",
  ".........kSSBBBBSSk.....",
  ".........kSSBWWBSSk.....",
  ".........kSSBBBBSSk.....",
  ".........kSSSSSSSSk.....",
  "........kSSSSSSSSSSk....",
  ".......kSSSSSSSSSSSSk...",
  "......kBBSSSSSSSSBBk....",
  ".....kBBBBSSSSSSBBBBk...",
  ".....kSSBBBBBBBBBBSSk...",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "...kSSSSSSSSSSSSSSSSSSk.",
  "...kSSSSSSSSSSSSSSSSSSk.",
  "...kSSBBBBBBBBBBBBSSk...",
  "...kSSBBBBBBBBBBBBSSk...",
  "....kSSBBBBBBBBBBSSk....",
  "....kSSBBBBBBBBBBSSk....",
  "....kSSBBBBBBBBBBSSk....",
  ".....kSSBBBBBBBBSSk.....",
  ".....kSSSSSSSSSSSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSSSSSSSSSSSk.....",
  "....kSSSSSSSSSSSSSSk....",
  "....kSSSSSSSSSSSSSSk....",
  "....kSSSSSSSSSSSSSSk....",
], _KW, _KH);

const K_WALK = _expand([
  "............kkkk........",
  "...........kRRRRk.......",
  "..........kRRRRRRk......",
  "..........kSSSSSSk......",
  ".........kSSBBBBSSk.....",
  ".........kSSBWWBSSk.....",
  ".........kSSBBBBSSk.....",
  ".........kSSSSSSSSk.....",
  "........kSSSSSSSSSSk....",
  ".......kSSSSSSSSSSSSk...",
  "......kBBSSSSSSSSBBk....",
  ".....kBBBBSSSSSSBBBBk...",
  ".....kSSBBBBBBBBBBSSk...",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "...kSSSSSSSSSSSSSSSSSSk.",
  "...kSSSSSSSSSSSSSSSSSSk.",
  "...kSSBBBBBBBBBBBBSSk...",
  "...kSSBBBBBBBBBBBBSSk...",
  "....kSSBBBBBBBBBBSSk....",
  "...kSSSSBBBBBBBBBBSSk...",
  "...kSSSSBBBBBBBBBBSSk...",
  "..kSSSSSSSSSSSSSSSSk....",
  "..kSSSSSSSSSSSSSSSSk....",
  "..kSSssssssssSSk........",
  "..kSSssssssssSSk........",
  "..kSSssssssssSSk........",
  ".kSSSSssssssssSSk.......",
  ".kSSSSSSSSSSSSSSk.......",
  "kSSSSSSSSSSSSSSSSk......",
  "kSSSSSSSSSSSSSSSSk......",
  "kSSSSSSSSSSSSSSSSk......",
], _KW, _KH);

const K_ATTACK = _expand([
  "............kkkk........",
  "...........kRRRRk.......",
  "..........kRRRRRRk......",
  "..........kSSSSSSk......",
  ".........kSSBBBBSSk.....",
  ".........kSSBWWBSSk.....",
  ".........kSSBBBBSSk.....",
  ".........kSSSSSSSSk.....",
  "........kSSSSSSSSSSk....",
  ".......kSSSSSSSSSSSSk...",
  "......kBBSSSSSSSSBBk....",
  ".....kBBBBSSSSSSBBBBk...",
  ".....kSSBBBBBBBBBBSSk...",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  "...kSSSSSSSSSSSSSSSSSSk.",
  "...kSSSSSSSSSSSSSSSSSSk.",
  "...kSSBBBBBBBBBBBBSSk...",
  "...kSSBBBBBBBBBBBBSSk...",
  "....kSSBBBBBBBBBBSSk....",
  "....kSSBBBBBBBBBBSSk....",
  "....kSSBBBBBBBBBBSSk....",
  ".....kSSBBBBBBBBSSk.....",
  ".....kSSSSSSSSSSSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSssssssssSSk.....",
  ".....kSSSSSSSSSSSSk.....",
  "....kSSSSSSSSSSSSSSk....",
  "....kSSSSSSSSSSSSSSk....",
  "....kSSSSSSSSSSSSSSk....",
], _KW, _KH);

const K_HIT = _expand([
  ".............kkkk.......",
  "............kRRRRk......",
  "...........kRRRRRRk.....",
  "...........kSSSSSSk.....",
  "..........kSSBBBBSSk....",
  "..........kSSBWWBSSk....",
  "..........kSSBBBBSSk....",
  "..........kSSSSSSSSk....",
  ".........kSSSSSSSSSSk...",
  "........kSSSSSSSSSSSSk..",
  ".......kBBSSSSSSSSBBk...",
  "......kBBBBSSSSSSBBBBk..",
  "......kSSBBBBBBBBBBSSk..",
  ".....kSSBBBBBBBBBBBBSSk.",
  ".....kSSBBBBBBBBBBBBSSk.",
  ".....kSSBBBBBBBBBBBBSSk.",
  ".....kSSBBBBBBBBBBBBSSk.",
  ".....kSSBBBBBBBBBBBBSSk.",
  "....kSSSSSSSSSSSSSSSSSSk",
  "....kSSSSSSSSSSSSSSSSSSk",
  "....kSSBBBBBBBBBBBBSSk..",
  "....kSSBBBBBBBBBBBBSSk..",
  ".....kSSBBBBBBBBBBSSk...",
  ".....kSSBBBBBBBBBBSSk...",
  ".....kSSBBBBBBBBBBSSk...",
  "......kSSBBBBBBBBSSk....",
  "......kSSSSSSSSSSSSk....",
  "......kSSssssssssSSk....",
  "......kSSssssssssSSk....",
  "......kSSssssssssSSk....",
  ".......kSSssssssssSSk...",
  ".......kSSSSSSSSSSSSk...",
  "......kSSSSSSSSSSSSSSk..",
  "......kSSSSSSSSSSSSSSk..",
  "......kSSSSSSSSSSSSSSk..",
], _KW, _KH);

// Knight death - armor collapsed on the ground, centered bottom
const K_DEATH = _expand([
  "           kkkk           ",
  "          kRRRRk          ",
  "         kRRRRRRk         ",
  "         kSSSSSSk         ",
  "        kSSBBBBSSk        ",
  "        kSSBWWBSSk        ",
  "        kSSBBBBSSk        ",
  "        kSSSSSSSSk        ",
  "       kSSSSSSSSSSk       ",
  "       kSSBBBBBBBBSSk     ",
  "       kSSBBBBBBBBSSk     ",
  "       kSSBBBBBBBBSSk     ",
  "       kSSBBBBBBBBSSk     ",
  "       kSSBBBBBBBBSSk     ",
  "       kSSSSSSSSSSSSk     ",
  "        kSSSSSSSSSSk      ",
  "        kSSssssssSSk      ",
  "        kSSssssssSSk      ",
  "        kSSssssssSSk      ",
  "        kSSSSSSSSSSk      ",
  "         kSSSSSSSSk       ",
  "         kSSSSSSSSk       ",
], 32, 22);

// ============================================================
// 2. RANGER (游侠) - 皮甲+兜帽, 短弓, 纤细敏捷
// ============================================================
const RANGER_PAL = { '.':0, 'k':1, 'G':2, 'g':3, 'Y':4, 'B':5, 'S':6, 'W':7 };

const _RW = 24, _RH = 33;

const R_IDLE = _expand([
  "..........kkkkkk........",
  ".........kYYYYYYk.......",
  ".........kYYYYYYk.......",
  ".........kYYYYYYk.......",
  "........kYYYYYYYYk......",
  "........kYYGWWGYYk......",
  "........kYYGGGGYYk......",
  "........kYYYYYYYYk......",
  "........kYYYYYYYYk......",
  ".......kYYYYYYYYYYk.....",
  ".......kGGGGGGGGGGk.....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  ".....kGGGGGGGGGGGGGGk...",
  ".....kGGGYGGGGGYGGGGk...",
  ".....kGGGGGGGGGGGGGGk...",
  ".....kGGGGGGGGGGGGGGk...",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  ".......kGGGGGGGGGGk.....",
  ".......kGGGGGGGGGGk.....",
  ".......kGGGBBBGGGk......",
  ".......kGGGBBBGGGk......",
  ".......kGGGBBBGGGk......",
  ".......kGGGBBBGGGk......",
  ".......kGGGGGGGGGGk.....",
  "........kGGGGGGGGk......",
  "........kGGGGGGGGk......",
  "........kGGGGGGGGk......",
], _RW, _RH);

const R_WALK = _expand([
  "..........kkkkkk........",
  ".........kYYYYYYk.......",
  ".........kYYYYYYk.......",
  ".........kYYYYYYk.......",
  "........kYYYYYYYYk......",
  "........kYYGWWGYYk......",
  "........kYYGGGGYYk......",
  "........kYYYYYYYYk......",
  "........kYYYYYYYYk......",
  ".......kYYYYYYYYYYk.....",
  ".......kGGGGGGGGGGk.....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  ".....kGGGGGGGGGGGGGGk...",
  ".....kGGGYGGGGGYGGGGk...",
  ".....kGGGGGGGGGGGGGGk...",
  "....kGGGGGGGGGGGGGGGk...",
  "....kGGGGGGGGGGGGGGGk...",
  ".....kGGGGGGGGGGGGGGk...",
  ".....kGGGGGGGGGGGGk.....",
  "....kGGGGGGGGGGGGGk.....",
  "....kGGGBBBGGGk.........",
  "....kGGGBBBGGGk.........",
  "....kGGGBBBGGGk.........",
  "...kGGGGBBBGGGk.........",
  "...kGGGGGGGGGGk.........",
  "..kGGGGGGGGGGGGk........",
  "..kGGGGGGGGGGGGk........",
  "..kGGGGGGGGGGGGk........",
  "..kGGGGGGGGGGGGk........",
], _RW, _RH);

const R_ATTACK = _expand([
  "..........kkkkkk........",
  ".........kYYYYYYk.......",
  ".........kYYYYYYk.......",
  ".........kYYYYYYk.......",
  "........kYYYYYYYYk......",
  "........kYYGWWGYYk......",
  "........kYYGGGGYYk......",
  "........kYYYYYYYYk......",
  "........kYYYYYYYYk......",
  ".......kYYYYYYYYYYk.....",
  ".......kGGGGGGGGGGk.....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  ".....kGGGGGGGGGGGGGGk...",
  ".....kGGGYGGGGGYGGGGk...",
  ".....kGGGGGGGGGGGGGGk...",
  ".....kGGGGGGGGGGGGGGk...",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  "......kGGGGGGGGGGGGk....",
  ".......kGGGGGGGGGGk.....",
  ".......kGGGGGGGGGGk.....",
  ".......kGGGBBBGGGk......",
  ".......kGGGBBBGGGk......",
  ".......kGGGBBBGGGk......",
  ".......kGGGBBBGGGk......",
  ".......kGGGGGGGGGGk.....",
  "........kGGGGGGGGk......",
  "........kGGGGGGGGk......",
  "........kGGGGGGGGk......",
], _RW, _RH);

const R_HIT = _expand([
  "...........kkkkkk.......",
  "..........kYYYYYYk......",
  "..........kYYYYYYk......",
  "..........kYYYYYYk......",
  ".........kYYYYYYYYk.....",
  ".........kYYGWWGYYk.....",
  ".........kYYGGGGYYk.....",
  ".........kYYYYYYYYk.....",
  ".........kYYYYYYYYk.....",
  "........kYYYYYYYYYYk....",
  "........kGGGGGGGGGGk....",
  ".......kGGGGGGGGGGGGk...",
  ".......kGGGGGGGGGGGGk...",
  ".......kGGGGGGGGGGGGk...",
  ".......kGGGGGGGGGGGGk...",
  ".......kGGGGGGGGGGGGk...",
  "......kGGGGGGGGGGGGGGk..",
  "......kGGGYGGGGGYGGGGk..",
  "......kGGGGGGGGGGGGGGk..",
  "......kGGGGGGGGGGGGGGk..",
  ".......kGGGGGGGGGGGGk...",
  ".......kGGGGGGGGGGGGk...",
  ".......kGGGGGGGGGGGGk...",
  "........kGGGGGGGGGGk....",
  "........kGGGGGGGGGGk....",
  "........kGGGBBBGGGk.....",
  "........kGGGBBBGGGk.....",
  "........kGGGBBBGGGk.....",
  "........kGGGBBBGGGk.....",
  "........kGGGGGGGGGGk....",
  ".........kGGGGGGGGk.....",
  ".........kGGGGGGGGk.....",
  ".........kGGGGGGGGk.....",
], _RW, _RH);

// Ranger death - collapsed on the ground
const R_DEATH = _expand([
  "        kkkkkk        ",
  "       kYYYYYYk       ",
  "       kYYYYYYk       ",
  "       kYYYYYYk       ",
  "      kYYYYYYYYk      ",
  "      kYYGWWGYYk      ",
  "      kYYGGGGYYk      ",
  "      kYYYYYYYYk      ",
  "      kYYYYYYYYk      ",
  "     kYYYYYYYYYYk     ",
  "     kGGGGGGGGGGk     ",
  "    kGGGGGGGGGGGGk    ",
  "    kGGGGGGGGGGGGk    ",
  "    kGGGGGGGGGGGGk    ",
  "    kGGGGGGGGGGGGk    ",
  "    kGGGGGGGGGGGGk    ",
  "   kGGGGGGGGGGGGGGk   ",
  "   kGGGYGGGGGYGGGGk   ",
  "   kGGGGGGGGGGGGGGk   ",
  "   kGGGGGGGGGGGGGGk   ",
  "    kGGGGGGGGGGGGk    ",
  "    kGGGGGGGGGGGGk    ",
  "    kGGGGGGGGGGGGk    ",
  "     kGGGGGGGGGGk     ",
  "     kGGGGGGGGGGk     ",
  "     kGGGBBBGGGk      ",
  "     kGGGBBBGGGk      ",
  "     kGGGBBBGGGk      ",
  "     kGGGBBBGGGk      ",
  "     kGGGGGGGGGGk     ",
  "      kGGGGGGGGk      ",
  "      kGGGGGGGGk      ",
  "      kGGGGGGGGk      ",
], 24, 33);

// ============================================================
// 3. MAGE (法师) - 深紫长袍+尖顶帽, 法杖, 周身水晶
// ============================================================
const MAGE_PAL = { '.':0, 'k':1, 'P':2, 'p':3, 'Y':4, 'C':5, 'W':6, 'g':7 };

const _MW = 26, _MH = 37;

const M_IDLE = _expand([
  ".............kkkk.........",
  "............kPPPPk........",
  "...........kPPPPPPk.......",
  "...........kPPPPPPk.......",
  "...........kPPPPPPk.......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  ".........kPPPPPPPPPPk.....",
  ".........kPPWkWWPPk.......",
  ".........kPPWWWWPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
], _MW, _MH);

const M_WALK = _expand([
  ".............kkkk.........",
  "............kPPPPk........",
  "...........kPPPPPPk.......",
  "...........kPPPPPPk.......",
  "...........kPPPPPPk.......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  ".........kPPPPPPPPPPk.....",
  ".........kPPWkWWPPk.......",
  ".........kPPWWWWPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
], _MW, _MH);

const M_ATTACK = _expand([
  ".............kkkk.........",
  "............kPPPPk........",
  "...........kPPPPPPk.......",
  "...........kPPPPPPk.......",
  "...........kPPPPPPk.......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  "..........kPPPPPPPPk......",
  ".........kPPPPPPPPPPk.....",
  ".........kPPWkWWPPk.......",
  ".........kPPWWWWPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  ".......kPPPPPPPPPPPPk.....",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  "........kPPPPPPPPPPk......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
], _MW, _MH);

const M_HIT = _expand([
  "............kkkk..........",
  "...........kPPPPk.........",
  "..........kPPPPPPk........",
  "..........kPPPPPPk........",
  "..........kPPPPPPk........",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  ".........kPPPPPPPPk.......",
  "........kPPPPPPPPPPk......",
  "........kPPWkWWPPk........",
  "........kPPWWWWPPk........",
  "........kPPPPPPPPk........",
  "........kPPPPPPPPk........",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  "......kPPPPPPPPPPPPk......",
  "......kPPPPPPPPPPPPk......",
  "......kPPPPPPPPPPPPk......",
  "......kPPPPPPPPPPPPk......",
  "......kPPPPPPPPPPPPk......",
  "......kPPPPPPPPPPPPk......",
  "......kPPPPPPPPPPPPk......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  ".......kPPPPPPPPPPk.......",
  "........kPPPPPPPPk........",
  "........kPPPPPPPPk........",
  "........kPPPPPPPPk........",
], _MW, _MH);

// Mage death - collapsed on the ground
const M_DEATH = _expand([
  "          kkkk          ",
  "         kPPPPk         ",
  "        kPPPPPPk        ",
  "        kPPPPPPk        ",
  "        kPPPPPPk        ",
  "       kPPPPPPPPk       ",
  "       kPPPPPPPPk       ",
  "       kPPPPPPPPk       ",
  "       kPPPPPPPPk       ",
  "       kPPPPPPPPk       ",
  "       kPPPPPPPPk       ",
  "      kPPPPPPPPPPk      ",
  "      kPPWkWWPPk        ",
  "      kPPWWWWPPk        ",
  "      kPPPPPPPPk        ",
  "      kPPPPPPPPk        ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "    kPPPPPPPPPPPPk      ",
  "    kPPPPPPPPPPPPk      ",
  "    kPPPPPPPPPPPPk      ",
  "    kPPPPPPPPPPPPk      ",
  "    kPPPPPPPPPPPPk      ",
  "    kPPPPPPPPPPPPk      ",
  "    kPPPPPPPPPPPPk      ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "     kPPPPPPPPPPk       ",
  "      kPPPPPPPPk        ",
  "      kPPPPPPPPk        ",
  "      kPPPPPPPPk        ",
], 26, 37);

// ============================================================
// 4. NINJA (忍者) - 黑色紧身衣+红围巾, 苦无, 太刀
// ============================================================
const NINJA_PAL = { '.':0, 'k':1, 'N':2, 'n':3, 'R':4, 'S':5, 'W':6 };

const _NW = 24, _NH = 34;

const N_IDLE = _expand([
  "..........kkkkkk........",
  ".........kNNNNNNk.......",
  ".........kNNNNNNk.......",
  ".........kNNNNNNk.......",
  "........kNNNNNNNNk......",
  "........kNNWkkWNNk......",
  "........kNNNNNNNNk......",
  "........kNNNNNNNNk......",
  "........kNNNNNNNNk......",
  ".......kRRRRRRRRRRk.....",
  ".......kNNNNNNNNNNk.....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  ".......kNNNNNNNNNNk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  "........knnnnnnnnk......",
  "........knnnnnnnnk......",
  "........knnnnnnnnk......",
  "........knnnnnnnnk......",
], _NW, _NH);

const N_WALK = _expand([
  "..........kkkkkk........",
  ".........kNNNNNNk.......",
  ".........kNNNNNNk.......",
  ".........kNNNNNNk.......",
  "........kNNNNNNNNk......",
  "........kNNWkkWNNk......",
  "........kNNNNNNNNk......",
  "........kNNNNNNNNk......",
  "........kNNNNNNNNk......",
  ".......kRRRRRRRRRRk.....",
  ".......kNNNNNNNNNNk.....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  ".......kNNNNNNNNNNk.....",
  "......knnnnnnnnnnnnk....",
  "......knnnnnnnnnnnnk....",
  "......knnnnnnnnnnnnk....",
  ".....knnnnnnnnnnnnnk....",
  ".....knnnnnnnnnnnnnk....",
  "....knnnnnnnnnnnnnnk....",
  "....knnnnnnnnnnnnnnk....",
  "....knnnnnnnnnnnnnnk....",
  "....knnnnnnnnnnnnnnk....",
  "....knnnnnnnnnnnnnnk....",
], _NW, _NH);

const N_ATTACK = _expand([
  "..........kkkkkk........",
  ".........kNNNNNNk.......",
  ".........kNNNNNNk.......",
  ".........kNNNNNNk.......",
  "........kNNNNNNNNk......",
  "........kNNWkkWNNk......",
  "........kNNNNNNNNk......",
  "........kNNNNNNNNk......",
  "........kNNNNNNNNk......",
  ".......kRRRRRRRRRRk.....",
  ".......kNNNNNNNNNNk.....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  ".....kNNNNNNNNNNNNNNk...",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  "......kNNNNNNNNNNNNk....",
  ".......kNNNNNNNNNNk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  ".......knnnnnnnnnnk.....",
  "........knnnnnnnnk......",
  "........knnnnnnnnk......",
  "........knnnnnnnnk......",
  "........knnnnnnnnk......",
], _NW, _NH);

const N_HIT = _expand([
  "...........kkkkkk.......",
  "..........kNNNNNNk......",
  "..........kNNNNNNk......",
  "..........kNNNNNNk......",
  ".........kNNNNNNNNk.....",
  ".........kNNWkkWNNk.....",
  ".........kNNNNNNNNk.....",
  ".........kNNNNNNNNk.....",
  ".........kNNNNNNNNk.....",
  "........kRRRRRRRRRRk....",
  "........kNNNNNNNNNNk....",
  ".......kNNNNNNNNNNNNk...",
  ".......kNNNNNNNNNNNNk...",
  ".......kNNNNNNNNNNNNk...",
  ".......kNNNNNNNNNNNNk...",
  ".......kNNNNNNNNNNNNk...",
  "......kNNNNNNNNNNNNNNk..",
  "......kNNNNNNNNNNNNNNk..",
  "......kNNNNNNNNNNNNNNk..",
  "......kNNNNNNNNNNNNNNk..",
  ".......kNNNNNNNNNNNNk...",
  ".......kNNNNNNNNNNNNk...",
  ".......kNNNNNNNNNNNNk...",
  "........kNNNNNNNNNNk....",
  "........knnnnnnnnnnk....",
  "........knnnnnnnnnnk....",
  "........knnnnnnnnnnk....",
  "........knnnnnnnnnnk....",
  "........knnnnnnnnnnk....",
  ".........knnnnnnnnnk....",
  ".........knnnnnnnnk.....",
  ".........knnnnnnnnk.....",
  ".........knnnnnnnnk.....",
  ".........knnnnnnnnk.....",
], _NW, _NH);

// Ninja death - collapsed on the ground
const N_DEATH = _expand([
  "        kkkkkk        ",
  "       kNNNNNNk       ",
  "       kNNNNNNk       ",
  "       kNNNNNNk       ",
  "      kNNNNNNNNk      ",
  "      kNNWkkWNNk      ",
  "      kNNNNNNNNk      ",
  "      kNNNNNNNNk      ",
  "      kNNNNNNNNk      ",
  "     kRRRRRRRRRRk     ",
  "     kNNNNNNNNNNk     ",
  "    kNNNNNNNNNNNNk    ",
  "    kNNNNNNNNNNNNk    ",
  "    kNNNNNNNNNNNNk    ",
  "    kNNNNNNNNNNNNk    ",
  "    kNNNNNNNNNNNNk    ",
  "   kNNNNNNNNNNNNNNk   ",
  "   kNNNNNNNNNNNNNNk   ",
  "   kNNNNNNNNNNNNNNk   ",
  "   kNNNNNNNNNNNNNNk   ",
  "    kNNNNNNNNNNNNk    ",
  "    kNNNNNNNNNNNNk    ",
  "    kNNNNNNNNNNNNk    ",
  "     kNNNNNNNNNNk     ",
  "     knnnnnnnnnnk     ",
  "     knnnnnnnnnnk     ",
  "     knnnnnnnnnnk     ",
  "     knnnnnnnnnnk     ",
  "     knnnnnnnnnnk     ",
  "     knnnnnnnnnnk     ",
  "      knnnnnnnnk      ",
  "      knnnnnnnnk      ",
  "      knnnnnnnnk      ",
  "      knnnnnnnnk      ",
], 24, 34);

// ============================================================
// 导出所有精灵
// ============================================================
const CHAR_SPRITES = {
  knight: {
    pal: KNIGHT_PAL,
    sprites: {
      idle: K_IDLE,
      walk: K_WALK,
      attack: K_ATTACK,
      hit: K_HIT,
      death: K_DEATH,
    },
  },
  ranger: {
    pal: RANGER_PAL,
    sprites: {
      idle: R_IDLE,
      walk: R_WALK,
      attack: R_ATTACK,
      hit: R_HIT,
      death: R_DEATH,
    },
  },
  mage: {
    pal: MAGE_PAL,
    sprites: {
      idle: M_IDLE,
      walk: M_WALK,
      attack: M_ATTACK,
      hit: M_HIT,
      death: M_DEATH,
    },
  },
  ninja: {
    pal: NINJA_PAL,
    sprites: {
      idle: N_IDLE,
      walk: N_WALK,
      attack: N_ATTACK,
      hit: N_HIT,
      death: N_DEATH,
    },
  },
};

// 解析所有精灵为整数数组格式
const CHAR_SPRITES_PARSED = {};
for (const [charName, charData] of Object.entries(CHAR_SPRITES)) {
  CHAR_SPRITES_PARSED[charName] = {};
  for (const [animName, strArr] of Object.entries(charData.sprites)) {
    CHAR_SPRITES_PARSED[charName][animName] = parseSprite(strArr, charData.pal);
  }
}

// 浏览器环境兼容
if (typeof window !== 'undefined') {
  window.KNIGHT_PAL = KNIGHT_PAL;
  window.RANGER_PAL = RANGER_PAL;
  window.MAGE_PAL = MAGE_PAL;
  window.NINJA_PAL = NINJA_PAL;
  window.KNIGHT_IDLE = K_IDLE;
  window.KNIGHT_WALK = K_WALK;
  window.KNIGHT_ATTACK = K_ATTACK;
  window.KNIGHT_HIT = K_HIT;
  window.KNIGHT_DEATH = K_DEATH;
  window.RANGER_IDLE = R_IDLE;
  window.RANGER_WALK = R_WALK;
  window.RANGER_ATTACK = R_ATTACK;
  window.RANGER_HIT = R_HIT;
  window.RANGER_DEATH = R_DEATH;
  window.MAGE_IDLE = M_IDLE;
  window.MAGE_WALK = M_WALK;
  window.MAGE_ATTACK = M_ATTACK;
  window.MAGE_HIT = M_HIT;
  window.MAGE_DEATH = M_DEATH;
  window.NINJA_IDLE = N_IDLE;
  window.NINJA_WALK = N_WALK;
  window.NINJA_ATTACK = N_ATTACK;
  window.NINJA_HIT = N_HIT;
  window.NINJA_DEATH = N_DEATH;
  window.CHAR_SPRITES = CHAR_SPRITES;
  window.CHAR_SPRITES_PARSED = CHAR_SPRITES_PARSED;
  window.parseSprite = parseSprite;
}